import { writeFileSync } from 'fs';
import { join, basename } from 'path';
import type { ComparisonResult } from './image-comparer.js';
import type { ScannedFile } from './file-scanner.js';

/**
 * Generates a Markdown report with visual diff results
 * @param comparisonResults - Results from comparing matched image pairs
 * @param baselineOnly - Files that exist only in baseline
 * @param candidateOnly - Files that exist only in candidate
 * @param outputDir - Directory where the report file will be written
 */
export function generateReport(
  comparisonResults: ComparisonResult[],
  baselineOnly: ScannedFile[],
  candidateOnly: ScannedFile[],
  outputDir: string,
): void {
  const markdown = generateMarkdown(comparisonResults, baselineOnly, candidateOnly);
  writeFileSync(join(outputDir, 'OUTPUT.md'), markdown);
}

/**
 * Helper to create markdown sections
 */
class MarkdownBuilder {
  private content: string[] = [];

  heading(level: number, text: string): this {
    this.content.push(`${'#'.repeat(level)} ${text}\n`);
    return this;
  }

  paragraph(text: string): this {
    this.content.push(`${text}\n`);
    return this;
  }

  list(items: string[]): this {
    items.forEach((item) => this.content.push(`- ${item}\n`));
    this.content.push('\n');
    return this;
  }

  image(alt: string, src: string): this {
    this.content.push(`![${alt}](${src})\n`);
    return this;
  }

  bold(text: string): string {
    return `**${text}**`;
  }

  divider(): this {
    this.content.push('\n---\n');
    return this;
  }

  newline(): this {
    this.content.push('\n');
    return this;
  }

  build(): string {
    return this.content.join('');
  }
}

/**
 * Generates the markdown content for the report
 */
function generateMarkdown(
  comparisonResults: ComparisonResult[],
  baselineOnly: ScannedFile[],
  candidateOnly: ScannedFile[],
): string {
  const md = new MarkdownBuilder();

  // Separate results into categories
  const withDifferences = comparisonResults.filter((r) => r.hasDifference);
  const withoutDifferences = comparisonResults.filter((r) => !r.hasDifference);

  // Calculate totals
  const totalImages = comparisonResults.length + baselineOnly.length + candidateOnly.length;
  const diffCount = withDifferences.length;
  const removedCount = baselineOnly.length;
  const addedCount = candidateOnly.length;

  // Determine status
  const hasFailed = diffCount > 0 || removedCount > 0;
  const statusEmoji = hasFailed ? '❌' : '✅';
  const statusText = hasFailed ? 'FAILED' : 'PASSED';

  // Header and summary
  md.heading(1, 'Visual Diff Report')
    .newline()
    .paragraph(`${md.bold('Status:')} ${statusEmoji} ${statusText}`)
    .newline()
    .heading(2, 'Summary')
    .newline()
    .list([
      `${md.bold('Total Images:')} ${totalImages}`,
      `${md.bold('Different:')} ${diffCount}`,
      `${md.bold('Removed:')} ${removedCount}`,
      `${md.bold('Added:')} ${addedCount}`,
      `${md.bold('Identical:')} ${withoutDifferences.length}`,
    ]);

  // Images with differences
  if (withDifferences.length > 0) {
    md.heading(2, `Images with Differences (${withDifferences.length})`).newline();

    withDifferences.forEach((result) => {
      const diffImageName = basename(result.diffImagePath);
      md.heading(3, result.name)
        .newline()
        .paragraph(`${md.bold('Difference:')} ${result.diffPercentage.toFixed(2)}%`)
        .newline()
        .image(`${result.name} diff`, diffImageName)
        .newline();
    });
  }

  // Missing or new files
  if (baselineOnly.length > 0 || candidateOnly.length > 0) {
    md.heading(2, 'Missing or New Files').newline();

    if (baselineOnly.length > 0) {
      md.heading(3, `Removed from Candidate (${baselineOnly.length})`).newline();
      md.list(baselineOnly.map((file) => file.name));
    }

    if (candidateOnly.length > 0) {
      md.heading(3, `Added in Candidate (${candidateOnly.length})`).newline();
      md.list(candidateOnly.map((file) => file.name));
    }
  }

  // Identical images
  if (withoutDifferences.length > 0) {
    md.heading(2, `Identical Images (${withoutDifferences.length})`)
      .newline()
      .list(withoutDifferences.map((result) => result.name));
  }

  // Footer
  md.divider().newline().paragraph('*Generated by visual-differ*');

  return md.build();
}
